//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:3aeae7b0-5e6b-4fec-a7c7-42dddccb78fd
    public partial class UIHomePanel
    {
        
        public const string NAME = "UIHomePanel";
        
        // 主界面管理器
        [SerializeField()]
        public MainController Main;
        
        private UIHomePanelData mPrivateData = null;
        
        public UIHomePanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        UIHomePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIHomePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Main = null;
            mData = null;
        }
    }
}
