//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:1d9f50ff-3de3-4575-b0ba-d07234cbb80e
    public partial class ClickPanel
    {
        
        public const string NAME = "ClickPanel";
        
        // 颜色变化按钮
        [SerializeField()]
        public UnityEngine.UI.Button ClickColorButton;
        
        private ClickPanelData mPrivateData = null;
        
        public ClickPanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        ClickPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new ClickPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ClickColorButton = null;
            mData = null;
        }
    }
}
